EMOTICON_MAPPING = {
    # Positive emoticons
    r':\)+': "GOOD",
    r':-?\)+': "GOOD",
    r';\)+': "GOOD",
    r';-?\)+': "GOOD",
    r'=\)+': "GOOD",
    r'\(?\b\d{1,3}%\b\)+': "GOOD",
    r'&lt;3+': "GOOD",
    r'&gt;:\)+': "GOOD",
    r'&gt;:-?\)+': "GOOD",
    r'&amp;gt;:\)+': "GOOD",
    r'&amp;gt;:-?\)+': "GOOD",
    r'\bxD\b': "GOOD",
    r'\bXD\b': "GOOD",
    r'\b&lt;3\b': "GOOD",
    r'\b&lt;:D\b': "GOOD",
    r'\b&lt;:-D\b': "GOOD",
    r'\b&lt;=D\b': "GOOD",
    r'\b&lt;=3\b': "GOOD",
    r'\b&lt;3\b': "GOOD",
    r'\b:heart:\b': "GOOD",
    r'\b:hearts:\b': "GOOD",
    r'\b:\+\)\b': "GOOD",
    r'\b:blush:\b': "GOOD",
    r'\b:heart_eyes:\b': "GOOD",
    r'\b:hearteyes:\b': "GOOD",
    r'\b:heart_eyes_cat:\b': "GOOD",
    r'\b:hearteyes_cat:\b': "GOOD",
    r'\b:heartpulse:\b': "GOOD",
    r'\b:heart_suit:\b': "GOOD",
    r'\b:heartsuit:\b': "GOOD",
    r'\b:thumbsup:\b': "GOOD",
    r'\b:clap:\b': "GOOD",
    r'\b:fire:\b': "GOOD",
    r'\b:100:\b': "GOOD",
    r'\b:star:\b': "GOOD",
    r'\b:star2:\b': "GOOD",
    
    # Negative emoticons
    r':\(+': "BAD",
    r':-?\(+': "BAD",
    r':\[': "BAD",
    r':-\[': "BAD",
    r':{': "BAD",
    r':-?{': "BAD",
    r';\(+': "BAD",
    r';-?\(+': "BAD",
    r'=\(+': "BAD",
    r'>:\[': "BAD",
    r'>:-?\[': "BAD",
    r'>:\(': "BAD",
    r'>:-?\(': "BAD",
    r'\bT.T\b': "BAD",
    r'\b:-?[\\|/]': "BAD",
    r'\bD:\b': "BAD",
    r'\bD:<\b': "BAD",
    r'\bd:\b': "BAD",
    r'\bd:<\b': "BAD",
    r'\b:angry:\b': "BAD",
    r'\b:rage:\b': "BAD",
    r'\b:scream:\b': "BAD",
    r'\b:worried:\b': "BAD",
    r'\b:cry:\b': "BAD",
    r'\b:sob:\b': "BAD",
    r'\b:disappointed:\b': "BAD",
    r'\b:disappoint:\b': "BAD",
    r'\b:disappointed_relieved:\b': "BAD",
    r'\b:pensive:\b': "BAD",
    r'\b:confused:\b': "BAD",
    r'\b:worried:\b': "BAD",
    r'\b:frowning:\b': "BAD",
    r'\b:anguished:\b': "BAD",
    r'\b:weary:\b': "BAD",
    r'\b:grimacing:\b': "BAD",
    r'\b:unamused:\b': "BAD",
    r'\b:rolling_eyes:\b': "BAD",
    r'\b:face_with_symbols_over_mouth:\b': "BAD",
    r'\b:face_with_symbols_on_mouth:\b': "BAD",
    r'\b:face_with_raised_eyebrow:\b': "BAD",
    r'\b:face_with_monocle:\b': "BAD",
    r'\b:expressionless:\b': "BAD",
    r'\b:neutral_face:\b': "BAD",
    r'\b:thumbsdown:\b': "BAD",
    r'\b:facepalm:\b': "BAD",
    r'\b:skull:\b': "BAD",
    r'\b:skull_and_crossbones:\b': "BAD",

    # Neutral emoticons
    r':\|+': "NEUTRAL",
    r':-?\|+': "NEUTRAL",
    r'=\|+': "NEUTRAL",
    r':/': "NEUTRAL",
    r':-?\/': "NEUTRAL",
    r':\\': "NEUTRAL",
    r':-?\\': "NEUTRAL",

    # Special emoticons
    r'&lt;3+': "GOOD",
}

ABBREVIATION_MAPPING = {
    "u": "you",
    "r": "are",
    "y": "why",
    "cuz": "because",
    "thx": "thanks",
    "pls": "please",
    "plz": "please",
    "w/": "with",
    "btw": "by the way",
    "b4": "before",
    "gr8": "great",
    "l8r": "later",
    "ttyl": "talk to you later",
    "s": "is",
    "wasn't": "was not",
    "weren't": "were not",
    "aren't": "are not",
    "haven't": "have not",
    "hasn't": "has not",
    "hadn't": "had not",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "can't": "cannot",
    "couldn't": "could not",
    "shouldn't": "should not",
    "wouldn't": "would not",
    "it's": "it is",
    "that's": "that is",
    "there's": "there is",
    "here's": "here is",
    "i'm": "i am",
    "we're": "we are",
    "you're": "you are",
    "they're": "they are",
    "he's": "he is",
    "she's": "she is",
    "i've": "i have",
    "we've": "we have",
    "you've": "you have",
    "they've": "they have",
    "could've": "could have",
    "should've": "should have",
    "would've": "would have",
    "must've": "must have",
    "client's": "client's" # handle apostrophe indicating possession
}
